import:
  - /home/abdugani/.config/alacritty/fonts.yml

## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 84
    lines: 28

  padding:
    x: 10
    y: 10

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

  ## scrolling
  history: 10000
  multiplier: 3

  ## Background opacity
  opacity: 0.92

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  # Bright colors
  bright:
    black: '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#ffffff'
theme: One-Dark
